### ISSUE TITLE
docker-compose up -d 在windows下不能正常工作

### ISSUE THREAD

**Issue by witskeeper** [netcorepal/d3shop#35]
1. 在windows部分容器无法启动
2. 基础设施与默认配置不匹配，需要修改配置，才能正常启动调试

**Comment by ZUOXIANGE** [comment]
我测试了一下,redis是OK的,MySQL错误是因为[这个](https://stackoverflow.com/questions/78445419/unknown-variable-default-authentication-plugin-mysql-native-password),可以按照这个修改,或者指定一下MySQL的版本tag

**Comment by witskeeper** [comment]
> 我测试了一下,redis是OK的,MySQL错误是因为[这个](https://stackoverflow.com/questions/78445419/unknown-variable-default-authentication-plugin-mysql-native-password),可以按照这个修改,或者指定一下MySQL的版本tag ![image](https://private-user-images.githubusercontent.com/20124439/381031682-fa48359b-22a9-4e89-b015-33aa5afee1da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDg0NzQsIm5iZiI6MTczMDIwODE3NCwicGF0aCI6Ii8yMDEyNDQzOS8zODEwMzE2ODItZmE0ODM1OWItMjJhOS00ZTg5LWIwMTUtMzNhYTVhZmVlMWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDEzMjI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMDgzN2QzZGI2MTAwNDI5ODk3OWU4MjRiYmQxNmM1ZDZhM2NmZGMxMzNjZThkOGQ3ODA0ZjM0MDIxMzhmNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.V6jQJSOzjA4aKSquPji46-KctipFrMDLcBEm1g0FWng)
> 
> ![image](https://private-user-images.githubusercontent.com/20124439/381031410-dbaa4a63-fd5f-4d0c-a7ae-6f2e56321d94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDg0NzQsIm5iZiI6MTczMDIwODE3NCwicGF0aCI6Ii8yMDEyNDQzOS8zODEwMzE0MTAtZGJhYTRhNjMtZmQ1Zi00ZDBjLWE3YWUtNmYyZTU2MzIxZDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDEzMjI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMWJiNGVmMDdlNjI1YjQ2Y2ZhM2I5MzQ0OWVhN2NiY2FkZmQ1ZDgzNzk3MzU3YjhkMjhiMTIwZmEyMjg3ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8JXQcezXFJ553UMRvlX5HQU3Rcr6de-71aLY3p0H8Mo)

确实如此

**Comment by coder-1jie** [comment]
> @coder-1jie redis 在windows下依然会报错，看起来下面这行是多余的 command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"

是的，移除后可以正常运行了
