### ISSUE TITLE
admin后台技术选型讨论

### ISSUE THREAD

**Issue by witskeeper** [netcorepal/d3shop#5]
- [x] antd blazor
- [ ] masa blazor
- [ ] other？

**Comment by carson-repository** [comment]
ant design vue + .net webapi

**Comment by ram16g** [comment]
antd blazor

**Comment by gowk** [comment]
element plus + vue3

**Comment by fokman** [comment]
antd blazor

**Comment by witskeeper** [comment]
看起来antd blazor，就这个把

**Comment by witskeeper** [comment]
@ElderJames
我们计划使用ant-design-blazor来作为这个项目后台管理的UI实现

**Comment by ElderJames** [comment]
@witskeeper  欢迎！期待一个实现 DDD 的项目诞生！还可以用 .NET Aspire 简化开发环境的服务依赖项~
