### ISSUE TITLE
C端技术选型

### ISSUE THREAD

**Issue by witskeeper** [netcorepal/d3shop#6]
这里讨论C端技术选型，前期主要考虑H5，下面是部分群友意见：

+ [ ] uniapp
+ [ ] taro
+ [ ] vue
+ [ ] react

**Comment by zhiyongLiang** [comment]
vue + Vant4

**Comment by fokman** [comment]
react

**Comment by witskeeper** [comment]
我们需要有前端方面的开发者支持

**Comment by witskeeper** [comment]
经过在直播中和大家的讨论，我们最终在H5版本选择vue来做
